# Generated by Django 5.1 on 2024-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0002_userprofile_alter_room_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='defaultuser', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
