# Generated by Django 5.1 on 2024-08-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0003_alter_message_sender_message_email_message_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='password',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
