# Generated by Django 5.1 on 2024-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0004_remove_message_email_remove_message_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='defaultuser', max_length=255, unique=True),
        ),
    ]
