# Generated by Django 5.1 on 2024-08-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0005_message_email_message_password_message_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='password',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
