# Generated by Django 5.1 on 2024-08-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
