# Generated by Django 5.1 on 2024-08-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0010_message_is_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_image',
        ),
    ]
