# Generated by Django 5.1 on 2024-08-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0013_remove_message_is_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
